---
title: "209 Project"
output: pdf_document
date: ""
---


```{r}
library(ggplot2)
```

```{r}
dat <- read.csv("data_cleaned.csv")
suicide <- read.csv("suicide_cleaned.csv")
happy <- read.csv("Happiness_cleaned.csv")
```

```{r}
boxplot(suicides.100k.pop ~ generation, data = suicide)
```
```{r}
boxplot(suicides.100k.pop ~ continent, data = suicide)
```
```{r}
plot(suicide$population, suicide$suicides.100k.pop)
```



```{r}
# Add this. This seems cool.
ggplot(data = suicide, aes(x = population, y = suicides_no, col = continent)) + geom_point()
```
```{r}
plot(happy[c("Happiness.Score", "Economy..GDP.per.Capita.", "Health..Life.Expectancy.")])
```


```{r}
# This seems pretty cool.
Multiple.Model <- lm(Happiness.Score ~ Economy..GDP.per.Capita. + Health..Life.Expectancy., data = happy)
Cm <- Multiple.Model$coefficients
Y.Pred.Multiple <- Cm[1] + Cm[2]*happy$Economy..GDP.per.Capita. + Cm[2]*happy$Health..Life.Expectancy.
Y.True <- happy$Happiness.Score
Economy.Model <- lm(Happiness.Score ~ Economy..GDP.per.Capita., data = happy)
Ce <- Economy.Model$coefficients
Life.Model <- lm(Happiness.Score ~ Health..Life.Expectancy., data = happy)
Cl <- Life.Model$coefficients
Y.Pred.Economy <- Ce[1] + Ce[2] * happy$Economy..GDP.per.Capita.
Y.Pred.Life <- Cl[1] + Cl[2] * happy$Health..Life.Expectancy.
mean((Y.Pred.Multiple - Y.True)^2)
mean((Y.Pred.Life - Y.True)^2)
mean((Y.Pred.Economy - Y.True)^2)
```
```{r}
Cm
```
We can see here that the Multiple Regression Model fits better than with just GDP per Capita or Life Expectancy.
We get the formula of Happiness Index as\
$Happiness Index \approx 3.10 + 1.51 * GDP + 1.46 * Life Expectancy$

```{r}
boxplot(Happiness.Score ~ Continent, data = happy)
```